//Inital list of places to render
var initialPlaces = [
{
  name: 'Piccadily Square',
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.5131699, lng: -0.144318515 },
  picture: '',
  liked: 'false',
  tags: 'soho, london, Piccadily',
},
{
  name: 'Camden Market',
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.5415018, lng: -0.1457217 },
  picture: '',
  liked: 'false',
  tags: 'camden, market, london',
},
{
  name: 'Portobello Market',
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.516952, lng: -0.2080111 },
  picture: '',
  liked: 'false',
  tags: 'portobello, market, london',
},
{
  name: 'Eiffel Tower',
  city: 'Paris',
  country: 'France',
  continent: 'Europe',
  location: { lat: 48.8583701, lng: 2.2922926 },
  picture: '',
  liked: 'false',
  tags: 'eiffel tower',
},
{
  name: 'Sacré-Cœur',
  city: 'Paris',
  country: 'France',
  continent: 'Europe',
  location: { lat: 48.8867046, lng: 2.3409156 },
  picture: '',
  liked: 'false',
  tags: 'Sacré-Cœur',
},
];
