//Inital list of places to render
var initialPlaces = [
{
  name: 'Piccadily Square',
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.5131699, lng: -0.144318515 },
  liked: 'false',
  tags: 'soho, london, Piccadily',
},
{
  name: 'Camden Market',
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.5415018, lng: -0.1457217 },
  liked: 'false',
  tags: 'camden, market, london',
},
{
  name: 'Portobello Market',
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.516952, lng: -0.2080111 },

  liked: 'false',
  tags: 'portobello, market, london',
},
{
  name: "St. Paul's Cathedral",
  city: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  location: { lat: 51.5138453, lng: -0.0983506 },
  liked: 'false',
  tags: 'st.pauls, cathedral, london',
},
{
  name: 'Eiffel Tower',
  city: 'Paris',
  country: 'France',
  continent: 'Europe',
  location: { lat: 48.8583701, lng: 2.2922926 },
  liked: 'false',
  tags: 'eiffel tower',
},
{
  name: 'Sacré-Cœur',
  city: 'Paris',
  country: 'France',
  continent: 'Europe',
  location: { lat: 48.8867046, lng: 2.3409156 },
  liked: 'false',
  tags: 'Sacré-Cœur',
},
{
  name: 'The Louvre',
  city: 'Paris',
  country: 'France',
  continent: 'Europe',
  location: { lat: 48.8606111, lng: 2.337644 },

  liked: 'false',
  tags: 'Louvre, Paris, Museum, Musée du Louvre',
},
{
  name: 'Notre Dame',
  city: 'Paris',
  country: 'France',
  continent: 'Europe',
  location: { lat: 48.852333, lng: 2.3482876 },

  liked: 'false',
  tags: 'Notre Dame, Paris, cathedral',
},
];
